name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: 'my_app'
      RUN_REGION: 'asia-east1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_environment_variables: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      # Print gcloud info
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # For debug pipeline
      - name: 'Debug'
        run: |
          echo $PROJECT_ID
          echo $SERVICE_NAME
          echo $GITHUB_SHA
          echo $RUN_REGION

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$$PROJECT_ID/$SERVICE_NAME/$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME/$GITHUB_SHA" \
            --platform "managed" \
            --port 80 \
            --allow-unauthenticated